export const testimonials = [
  {
    name: "Richard M.",
    company: "Irwin",
    role: "Director of Engineering",
    image: "https://app.axolo.co/images/richard.jpg",
    text: "We no longer need to cut and paste MR URLs into Slack manually. Axolo also reduces button-clicking in the GitLab UI, because Slack can be used to assign a Reviewer and also Approve an MR. We no longer need to watch for email notifications and context-switch to the GitLab UI to have the discussion -- Axolo automatically opens (and archives) a channel dedicated to the MR discussion.",
  },
  {
    company: "Sproutfi",
    name: "Tyler",
    role: "CTO",
    image: "https://axolo.s3.eu-west-3.amazonaws.com/communication/partners/human/tyler.jfif",
    text: "Code quality has improved, engineers have a better understanding of what their colleagues are working on, and code is getting shipped much faster. Time from pull request open to review to merge is WAY faster, and engagement with reviews is much higher for our team. Axolo's team is also unbelievably fast in resolving issues when we run into them. Pleasure to work with them.",
  },
  {
    company: "HeraldAPI",
    name: "Jacob",
    role: "CTO",
    image: "https://axolo.s3.eu-west-3.amazonaws.com/communication/partners/human/jacob.jfif",
    text: "Axolo is an incredible tool for connecting PRs with our everyday engineering discussion on Slack. It integrates seamlessly and makes it so as a manager, I never lose track of my engineers' work. For my engineers, it allows them to collaborate without losing a thread in different contexts. Overall it keeps us moving swiftly throughout the sprint and continuously reviewing and merging code!",
  },
  {
    company: "House Rx",
    name: "Dan",
    role: "Director of Infrastructure",
    image: "https://axolo.co/images/testimonials/dan.jpg",
    text: "Axolo has made it easier to hold developers and QA engineers accountable for reviewing and merging pull requests on a timely basis. Our average PR time-to-merge was 2.40 days before Axolo, this has been reduced to 1.51 days after only using it for 2 weeks.",
  },
  {
    company: "Weekday",
    name: "Anubhav Malik",
    role: "CTO",
    image: "https://axolo.s3.eu-west-3.amazonaws.com/communication/partners/human/a_malik.jpg",
    text: "We used to send each other our GitHub PR links on Slack to ask for a review. Having Axolo made it a zero-effort thing. Having discussions on Slack is much more natural and Axolo does a great job doing it. The support is amazing as well! Arthur and Sydney proactively reach out to ask if we're facing any issues and even released one feature request within hours!",
  },
  {
    company: "Juo.io",
    name: "Pawel",
    role: "CTO",
    image: "https://axolo.s3.eu-west-3.amazonaws.com/communication/partners/human/pawel.png",
    text: "Axolo is a must-have for teams using GitHub. My team can discuss pull requests without leaving Slack now. Axolo helped us merge pull requests faster in a more seamless way. I was waiting for this product for so long!",
  },
  {
    company: "Staqfi",
    name: "Dee Evans",
    image: "https://axolo.co//images/testimonials/dee.jpg",
    role: "CTO",
    text: "I've been a CTO at various companies for a decade now. One of my biggest pain points has always been PR review responsiveness. I've tried so many home baked solutions. Axolo is the app that solves the problem perfectly.",
  },
  {
    company: "Brickwise",
    name: "Valentin Perkonigg",
    image: "",
    role: "CTO",
    text: "Axolo helps us communicate in one tool and iterate fast on Merge Requests. Most open requests are closed within 1-2 days nowadays. We improved our development speed by good 20%.",
  },
  // {
  //   company: "",
  //   name: "",
  //   image: "",
  //   role: "",
  //   text: "",
  // },
]
